// <auto-generated />
namespace Class_13_Practices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class YasinA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(YasinA));
        
        string IMigrationMetadata.Id
        {
            get { return "202310081758121_YasinA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
